Vagrant.configure('2') do |config|
  config.vm.box = 'vimalkvn/linuxmint-20.1'
  config.vm.box_check_update = false

  config.vm.provider :virtualbox do |v, override|
    v.gui = true
    v.customize ['modifyvm', :id, '--name', 'LinuxMint 20.1']
    v.customize ['modifyvm', :id, '--memory', 2048]
    v.customize ['modifyvm', :id, '--cpus', 1]
    v.customize ['setextradata', 'global', 'GUI/MaxGuestResolution', 'any']
    v.customize ['modifyvm', :id, '--biosbootmenu', 'disabled']
    v.customize ['modifyvm', :id, '--boot1', 'disk']
    v.customize ['modifyvm', :id, '--boot2', 'none']
    v.customize ['modifyvm', :id, '--boot3', 'none']
    v.customize ['modifyvm', :id, '--boot4', 'none']
    v.customize ['modifyvm', :id, '--ioapic', 'on']
    v.customize ['modifyvm', :id, '--accelerate3d', 'on']
    v.customize ['modifyvm', :id, '--rtcuseutc', 'on']
    v.customize ['modifyvm', :id, '--clipboard', 'bidirectional']
  end
    
  config.vm.provision 'ansible_local' do |a|
    a.playbook = 'setup.yml'
    a.compatibility_mode = '2.0'
  end
end
